### ISSUE TITLE
upgrade botocore and boto3 versions

### ISSUE THREAD

**Issue by eranreshef** [terrycain/aioboto3#111]
* Async AWS SDK for Python version: 5.0.0
* Python version: 3.6.1
* Operating System: osX

### Description

Are you planning to upgrade your `botocore` and `boto3` dependencies anytime soon?
You are requiring `boto3>=1.4.7,<=1.7.58` while latest version is already 1.9.40 and `botocore>=1.10.58,<1.10.59` while latest version is already 1.12.40

Thanks

**Comment by terrycain** [comment]
I too am waiting for an aiobotocore update so i can use AWS Xray.
Once this PR aio-libs/aiobotocore/pull/639 gets merged, i'll update my deps accordingly.

**Comment by terrycain** [comment]
I've released 6.0.0 which allows botocore 1.12.24, currently i've copied aiobotocore into the project so we can move on. When they decide to update then i'll depend on their library again.

**Comment by eranreshef** [comment]
Works great!
Thanks!
