### ISSUE TITLE
Is it possible to upload to s3 asynchronously by chunks?

### ISSUE THREAD

**Issue by py-radicz** [terrycain/aioboto3#130]
What I am trying to do: I want to download file from remote source and upload it directly to s3 without storing the bytes on the localhost. (Stream the data from remote machine through my machine to s3). There are tens of files in remote location, thats why I want to use async lib, to stream all files simultaneously to save time.

Is it possible with current version of lib to do something like following?

```python
async with aioboto3.client('s3', loop=loop) as client:
    async for chunk in response.content.iter_chunked(1024):
        if chunk:
            # await put chunk into appropriate file handle on s3
```

Thanks for some pointers.

**Comment by terrycain** [comment]
If you stream to your machine, and have a file object you can do .read() on, you can pass a file object to s3.upload_fileobj that will perform a multipart upload.

```
async with aioboto3.client('s3', loop=loop) as client:
    await client.upload_fileobj(some_fileobj...)
```
