### ISSUE TITLE
how to use s3 download_file

### ISSUE THREAD

**Issue by francophongvu** [terrycain/aioboto3#137]
* Async AWS SDK for Python version: boto3 1.9.49
* Python version:3.6
* Operating System: Mac OS

### Description

I tried to download file from S3, and I received error:
`A Future or coroutine is required`

In the documentation, I cannot find how to use the S3 properly except DynamoDB. Is it worth to update the doc ?

### What I Did

```
async def download_files():
    async with aioboto3.resource('s3') as s3:
        await s3.meta.client.download_file(const.bucket_name, 'file/test.txt', '/tmp/test.txt')
        print('file downloaded')

def process():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(download_files())
    loop.close()

process()
```

**Comment by burrbank** [comment]
The documentation is a bit sparse, I managed to get s3 downloads working with using:

async def download_json(key):
    async with aioboto3.resource('s3') as s3:
        obj = s3.Object(const.bucket, key)
        result = await obj.get()
        result = await result['Body'].read()
    return json.loads(result.decode('utf-8'))['keys']

loop = asyncio.get_event_loop()
loop.run_until_complete(download_files())
# loop.close() # I had to skip this line, though I expect that was an issue with jupyter maybe.
```

**Comment by terrycain** [comment]
download_file works like you would expect now, it does not do multipart downloads but that has been requested in #131
