### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by madss** [terrycain/aioboto3#167]
### Description

I'm trying to evaluate whether to use aioboto3 for a project that will do multiple concurrent uploads to S3 using an `aioboto3.Session`. According to [the boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html?highlight=multithreading#multithreading-multiprocessing) sessions contains shared data and should not be shared in multiple threads. Is this also a problem in aioboto3 or is it safe to use a session multiple times concurrently? Since you claim aioboto3 is just a wrapper around boto3 I would expect it to be unsafe to use concurrently if the state is used to track the upload or similar.

**Comment by terrycain** [comment]
Well aioboto3 is based on the python async framework so there is only 1 thread, that being said, i've done many parallel uploads to s3 using this library by starting multiple coroutines and have seen no adverse effects as yet.

What are you trying to achieve?

**Comment by madss** [comment]
Thanks. I'll also only run a single thread, so the topic should probably have been _Concurrency Safety_ instead. Sorry about that.

Have you also used sessions? My worry is that when starting the first upload boto might save some state on my `session` or `client` object. Starting another upload before the first has finished would also save state to the same object overwriting the state from the first upload. Then when the first upload finishes it will look at the wrong state. In code:

```python
session = aioboto3.Session(...)
client = session.client('s3')

first_coro = client.put_object(Bucket='MyBucket', Key='key1', Body='Hello')
# if put_object saved e.g. 'MyBucket/key1' in the client object ...

second_coro = client.put_object(Bucket='MyBucket', Key='key2', Body='World')
# ... and 'MyBucket/key2' here ...

await first_coro
# ... then it might do some finalizing or cleanup work here based on 'MyBucket/key2' ...

await second_coro
# ... and here the second upload is already finalized or cleaned up, while the first never was
```

**Comment by terrycain** [comment]
OK so what you've done there is run the first_coro and once its finished started the 2nd. If you want to run them in parallel you would do something like
```python
await asyncio.gather(
    client.put_object(Bucket='MyBucket', Key='key1', Body='Hello'),
    client.put_object(Bucket='MyBucket', Key='key2', Body='Hello')
)
```

I've done this and have seen no sideeffects from doing so, when doing an upload with put_object there is not any state I'm aware of that would affect concurrent running so I think your good.

**Comment by madss** [comment]
No, they already run in parallel in my example ... I'm awaiting their result one after the other.

If you haven't experienced any problems, I'll also give it a try. Thanks for your input.
