### ISSUE TITLE
Feature request: concurrent upload

### ISSUE THREAD

**Issue by charleswhchan** [terrycain/aioboto3#170]
Looking at the code for `upload_fileobj()`, it appears `max_concurrency` is not used:
https://github.com/terrycain/aioboto3/blob/v6.3.0/aioboto3/s3/inject.py#L145

Compare the `_upload_parts()` in s3transfer, it would appear it should not be too difficult to add async concurrent upload:
https://github.com/boto/s3transfer/blob/dc28ff80658ab65b25d98872ab20afe8a56ad119/s3transfer/__init__.py#L398

Would love this feature to be add so we can maximize throughput during upload.

**Comment by terrycain** [comment]
I'll have a thing about it, it should be pretty easy to add

**Comment by terrycain** [comment]
Ok can you try out 427321936f1e7e9329ba76aac72106cfb0cc64b9 and see if that works well for you? I tested it here with a 1GiB file and seemed to max out my connection and successfully upload and the MD5 sums match.

**Comment by charleswhchan** [comment]
looks good to me 👍

**Comment by terrycain** [comment]
Cool I'll merge and release on monday (hopefully)

**Comment by terrycain** [comment]
Try v6.4.1
