### ISSUE TITLE
How to configure max connections?

### ISSUE THREAD

**Issue by mojimi** [terrycain/aioboto3#176]
Hello, is there a parameter where I can configure max connections of aiohttp connector?

This is very useful to rate limit concurrent lambda invocations

For example, in aiohttp you can configure this :

```python
conn = aiohttp.TCPConnector(limit=10, limit_per_host=10)
session = aiohttp.ClientSession(loop=loop, connector=conn)
```

**Comment by terrycain** [comment]
I think that's best asked in aiobotocore as that makes the client.
