### ISSUE TITLE
BatchGetItem

### ISSUE THREAD

**Issue by petergaultney** [terrycain/aioboto3#177]
Would you be interested in a PR that supports a background-thread-supported async batch get against a single table?

It's not really async all the way down - it spawns a single IO thread per table and does timed batching the the background, but it does offer an async interface that looks basically like this:

```
async def get_dynamo_item(
        table_name: str,
        primary_key_tuple: tuple,
        primary_key_attr_names: ty.Sequence[str] = ('id',),
        item_nicename: str = 'Item',
) -> dict:
    """Performs Dynamo request batching behind the scenes.

    The primary key tuple must be in the order defined by the primary_key_attr_names.

    This is guaranteed to be slower than just asking for a single item
    directly, because the batcher waits a short period to maximize the
    size of its batches, so only use this if you know your client code
    is going to be making multiple async requests.
    You should almost certainly wrap this function with a helper
    method for your given table and item type.
    """
    logger.debug(f'Asking for {primary_key_tuple}')
    fulfiller = ensure_table_request_fulfiller(table_name, primary_key_attr_names)
    fut = get_event_loop().create_future()
    fulfiller.request_map[fut] = primary_key_tuple
    await fulfiller.queue.put(fut)
    item = await fut
    return item
```

The inputs at this level are primary key tuples instead of the 'normal' keydicts
so that we can deduplicate them, as boto3 will not allow
duplicates within a batch, and different async users can't deduplicate against each other. 
This is why it is also necessary to
supply a parallel tuple of the names of the primary key
attributes. In many cases this will simply be ('id',), so the default is provided.

A table name is used instead of a TableResource so that we can pull the results from the proper part of the response.

It would be pretty trivial to write a wrapper that instead pulls this information (key schema and table name) from the TableResource and then extracts the keys from input dicts, to better match the `batch_get_items` interface itself.

I do have an entire implementation that's been running in production for ~6 months, so if you're interested, I could make a PR. It's Python 3.7 at the moment with static typing and whatnot, but that could be stripped. I'm not sure what versions of Python you need to support, and how much effort it would be to go back to, say, 3.3 or 2.7. And it depends on probably another ~500 lines of code that I haven't posted here. Again, it's backed by a worker thread, which might not be in scope for this library.

**Comment by terrycain** [comment]
Sorry have been away for quite a while. It does sound great, but it is out of scope somewhat. Then again so is the S3 crypto part I added to the library. I think for now we're good but I'll keep it in mind
