### ISSUE TITLE
Should I reuse resource?

### ISSUE THREAD

**Issue by tallesl** [terrycain/aioboto3#182]
In the example below, considering that `put_item` will be called multiple times during the lifetime of my application, should I store and reuse `dynamo_resource` or instantiate a new one for each call?

```py
 async with aioboto3.resource('dynamodb', region_name='eu-central-1') as dynamo_resource:
    table = dynamo_resource.Table('test_table')

    await table.put_item(
        Item={'pk': 'test1', 'col1': 'some_data'}
    )
```

**Comment by mvalkon** [comment]
I would be interested to understand this a little deeper myself; if we instantiate a new one, will it actually return a new one or is there some internal management of the resources? Or will it actually create a new resource? Latter sounds rather bad.

@tallesi did you find an answer to this on your own?

**Comment by terrycain** [comment]
If your going to run `with aioboto3.resource` or `with aioboto3.client` in a loop or have long running services then I'd suggest doing something like the following:

```python
a = aioboto3.client('s3')
# ... lots of stuff
await a.close()
```

As for the dynamo example above, I'd suggest also storing the table variable as well if its going to be used a lot.
