### ISSUE TITLE
dynamodb query with memory leak

### ISSUE THREAD

**Issue by aron-bordin** [terrycain/aioboto3#187]
* Async AWS SDK for Python version: 6.4.1
* Python version: Tested with Python 3.6.6, 3.7, and 3.8.1
* Operating System: Arch Linux

### Description

Code 1:
```
        def _query():
            res = boto3.resource('dynamodb')
            table = res.Table(config.METADATA_TABLE_NAME)
            return table.query(KeyConditionExpression=Key('namespace').eq(namespace))

        loop = asyncio.get_running_loop()
        response = await loop.run_in_executor(None, _query)
```
Code 2:
```

        async with aioboto3.resource('dynamodb') as dyn:
            table = dyn.Table(config.METADATA_TABLE_NAME)
            response = await table.query(KeyConditionExpression=Key('namespace').eq(namespace))
```

I use it to query around 5k namespaces. After 5k namespaces, Code 1 is consuming around 250MB, and Code 2 is using around 1.7 GB

**Comment by aron-bordin** [comment]
@terrycain do you have any idea of what is happening here? I'd love to solve this issue, but I'm not able to understand what is happening :/

**Comment by terrycain** [comment]
Ok so I inserted around 5million rows into dynamo the other day, and didnt notice anything. Can you create me a script and example dataset that i can use to reproduce this?
