### ISSUE TITLE
update to aiobotocore 0.12.0

### ISSUE THREAD

**Issue by sp-miguel-ibero** [terrycain/aioboto3#192]
`aiobotocore` 0.11 depends on `botocore` 1.13.14 which requires `python-dateutil<2.8.1` and that fails with python 3.7

**Comment by terrycain** [comment]
0.12.0 should depend on `'botocore>=1.15.3,<1.15.16',`, have you tried this on a fresh virtualenv?

I'll have a proper look later

**Comment by alexcarruthers** [comment]
We have some other dependencies that require aiobotocore 0.12.0 so having aioboto3 support it as well is essential. especially since 0.12.0 seems to fix some python 3.8 compatabilities

**Comment by terrycain** [comment]
v7.0.0 out :smile:
