### ISSUE TITLE
Onboard SQS as part of the arsenal of aioboto3

### ISSUE THREAD

**Issue by nrccua-timr** [terrycain/aioboto3#210]
I'd love for this library to include support for SQS as it is a basic and foundational service of AWS.  Last day or so I've spent to successful migrate from using boto3 to aioboto3 within a FastAPI applicaiton, utilizing dynamoDB and S3 aioboto3 functions.

**Comment by terrycain** [comment]
Nice!

So the base sqs client functions should work out the box, is there anything specific that doesn't?

**Comment by nrccua-timr** [comment]
This is good to know.  I don't remember seeing SQS mentioned in the docs and searched for it without luck in the repo, although I did see reference to it in aiobotocore.  When I have time I'll use the client to convert my boto3 funcs.  Thanks for responding!

**Comment by terrycain** [comment]
So pretty much all boto3 calls work as it's a glorified wrapper hence I didn't document them all :D

**Comment by nrccua-timr** [comment]
Here are some good examples, for anybody interested, using async with SQS:  https://aiobotocore.readthedocs.io/en/latest/examples.html

**Comment by bruceshell** [comment]
this is aiobotocore mate
