### ISSUE TITLE
Request to upgrade to latest aiobotocore verison. botocore version mismatch. 

### ISSUE THREAD

**Issue by Athul-R** [terrycain/aioboto3#221]
* Async AWS SDK for Python version: 
* Python version: 3.7 
* Operating System: Alpine Docker `python:3.7.7-alpine3.12`

### Description

Trying to install boto3 latest version `1.16.*` or `1.15.*` it has conflicts due to the botocore version. 

- aioboto3 depends on the aiobotocore v1.1.2. 
- aiobotocore v1.1.2 depends on botocore<1.17.45 and >=1.17.44 
- where as boto3 1.15.17 depends on botocore<1.19.0 and >=1.18.17. 
- Any boto3 version higher than 1.14.46 have this conflict. 

### The requirements.txt file 
```
aioboto3==8.2.0
boto3==1.15.17
```

### Logs 

```
The conflict is caused by:
    boto3 1.15.17 depends on botocore<1.19.0 and >=1.18.17
    aiobotocore[boto3] 1.1.2 depends on botocore<1.17.45 and >=1.17.44

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies


```

### Fix
When I update the aiobotocore version, and the boto3 version. It installs successfully without conflicts. 

```
boto3==1.16.*
aiobotocore==1.2.0
```

**Please upgrade to latest aiobotocore version.**

**Comment by terrycain** [comment]
aioboto3 brings in `aiobotocore[boto3]`, aiobotocore defines the boto3 version, you should not specify it directly. If you need a later version of boto3, please raise a request with aiobotocore to bump the boto3 dependencies.
