### ISSUE TITLE
Create VPC Flow Logs Documentation Request

### ISSUE THREAD

**Issue by jbcurtin** [terrycain/aioboto3#230]
* Async AWS SDK for Python version: latest
* Python version: 3.8 & 3.9
* Operating System: macOS, Linux, Windows

### Description

We'd like to enable some advanced features for AWS->EC2 using aioboto3. I can't seem to find documentation on how to enable VPC Flow Logs. After manually inspecting the ec2 resource object, it seems to not have methods required. Has `create_flow_logs` been omitted from the API or is it missing from the documentation?

* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_flow_logs

**Comment by terrycain** [comment]
9.0.0 is out, can you try with that
