### ISSUE TITLE
include python3.7 in aioboto3 version 9.X 

### ISSUE THREAD

**Issue by nrccua-timr** [terrycain/aioboto3#235]
Almost all python data science applications are running on python3.7 or 3.6 so this excludes any of those apps from leverage aioboto3.

**Comment by terrycain** [comment]
Ah good shout, the dropping of 3.7 was probably a bit hasty.

**Comment by nrccua-timr** [comment]
Thanks Terry.  Maybe it can be changed in the 9.2.0 version you have out in beta?



Tim Reichard
Senior Software Architect
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

ACT | NRCCUA
701 Brazos, 5th Floor<x-apple-data-detectors://1>
Austin, TX 78701<x-apple-data-detectors://1>

mobile:  512.573.5819


From: Terry Cain ***@***.***>
Date: Thursday, July 22, 2021 at 12:35 PM
To: terrycain/aioboto3 ***@***.***>
Cc: Tim Reichard ***@***.***>, Author ***@***.***>
Subject: Re: [terrycain/aioboto3] include python3.7 in aioboto3 version 9.X (#235)

Ah good shout, the dropping of 3.7 was probably a bit hasty.

**Comment by terrycain** [comment]
v9.2.0 should now work on 3.7

**Comment by nrccua-timr** [comment]
Thanks. Using it now

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
