### ISSUE TITLE
Fixing dependencies prevents their use by other libraries

### ISSUE THREAD

**Issue by Suor** [terrycain/aioboto3#238]
You have deps, like `aiobotocore` fixed to particular versions, which is not recommended for python libraries only for projects. The reason is if two libraries use the same dep and specify even slightly different versions, e.g. `1.3.2` and `1.3.3`, then no code might simultaneously use both libraries without violating their dependencies. Recent versions of `pip` will even refuse to install such libraries together.

The solution is to specify the most wide version range possible, i.e. `aiobotocore>=1.3.3,<2.0`. Here we rely on some bugfix in `1.3.3` and do not expect to work after non-backwards compatible change in `2.0`.

**Comment by terrycain** [comment]
The problem is, aiobotocore[boto3] depends on a specific version of boto3, of which this library is patching some of the methods, by relaxing that constraint could then result in newer versions of boto3 being pulled in which are incompatible.
