### ISSUE TITLE
Allow to raise Exceptions in Callback (upload_fileobj)

### ISSUE THREAD

**Issue by poul1x** [terrycain/aioboto3#239]
The current `Callback` use case it too narrow: just record upload progress. But It can be more broad.
Raising exceptions from `Callback` can be used to implement limiting the file upload size (in `upload_fileobj` ). When exception is caught, abort the file upload and reraise it.

**Comment by terrycain** [comment]
Would this work when using normal `boto3`? As mainly I want to try and remain compatible with that.

**Comment by poul1x** [comment]
Oh, it doesn't. Further discussion makes no sense
