### ISSUE TITLE
Why package is locked to specific versions of packages?

### ISSUE THREAD

**Issue by lesnik512** [terrycain/aioboto3#241]
Hi, thanks for this library!

I have a problem with dependabot saying me to update some dependencies, for example aiobotocore, but the problem is that aioboto3 seems to be locked on specific version of aiobotocore=1.3.3.
Are there problems with newer versions?

**Comment by terrycain** [comment]
Because this package patches specific methods of boto3 which aiobotocore brings in. Though you have reminded me I need up update it to 1.4.1

**Comment by terrycain** [comment]
v9.2.1 is out
