### ISSUE TITLE
Avoid installing Chalice as a dependency by default

### ISSUE THREAD

**Issue by and-semakin** [terrycain/aioboto3#242]
* Async AWS SDK for Python version: 9.2.1

### Description

As far as I can see, there is [experimental support for Chalice](https://github.com/terrycain/aioboto3/commit/be4ffd665a207a289d1ef25802fd90c1e147e841) now. I develop a traditional (I mean, not serverless) asynchronous ASGI web application. I don't need Chalice but `aioboto3` still installs it and seems like there is no easy way to avoid it.

I see, that you've already [defined `chalice` as an extra dependency](https://github.com/terrycain/aioboto3/blob/13c56a6a5a1a87f79c1b998cc76b01ce72fddaef/pyproject.toml#L32) but for some reason, it doesn't work.

See:

```sh
$ python -V
Python 3.9.7

$ pip -V
pip 21.2.3 from ./aioboto3_experiment/.venv/lib/python3.9/site-packages/pip (python 3.9)

$ pip install aioboto3
....

$ pip freeze
aioboto3==9.2.1
aiobotocore==1.4.2
aiohttp==3.7.4.post0
aioitertools==0.8.0
async-timeout==3.0.1
attrs==21.2.0
blessed==1.17.6
boto3==1.17.106
botocore==1.20.106
cffi==1.14.6
chalice==1.26.0
chardet==4.0.0
click==8.0.1
cryptography==35.0.0
idna==3.2
inquirer==2.7.0
jmespath==0.10.0
multidict==5.2.0
mypy-extensions==0.4.3
pycparser==2.20
python-dateutil==2.8.2
python-editor==1.0.4
PyYAML==5.4.1
readchar==2.0.1
s3transfer==0.4.2
six==1.16.0
typing-extensions==3.10.0.2
urllib3==1.26.7
wcwidth==0.2.5
wrapt==1.13.1
yarl==1.6.3

$ pip freeze | grep chalice
chalice==1.26.0
```

Note, I didn't request any extras but I still have chalice installed.

Thanks for your work by the way!

**Comment by terrycain** [comment]
Oh good spot. Yeah the version should not be in the extras section as that just specifies _which_ dependencies it should pull in.

**Comment by terrycain** [comment]
v9.2.2 is out :smile:

**Comment by terrycain** [comment]
Yep good shout
