### ISSUE TITLE
Needs to be updated to aiobotocore==2.0.0

### ISSUE THREAD

**Issue by rggjan** [terrycain/aioboto3#245]

**Comment by rudaporto** [comment]
This allows `aioboto3` to be used with Python 3.9 💟

**Comment by darwinshameran** [comment]
@terrycain Would really appreciate if this got merged. 💯

**Comment by rggjan** [comment]
2.0.1 is out...

**Comment by terrycain** [comment]
[9.3.0](https://pypi.org/project/aioboto3/) is out
