### ISSUE TITLE
There is no `copy_from` method for the `Object` object of `s3` resource

### ISSUE THREAD

**Issue by bubanoid** [terrycain/aioboto3#251]
* Async AWS SDK for Python version

details:

    aioboto3==9.3.0
    aiobotocore==2.0.1
    boto3==1.19.8
    botocore==1.22.8

* Python version

details:

    Python 3.9.6

* Operating System

details:

    macOS Monterrey
    Version 12.1 (21C52)

### Description

There is no `copy_from` method for the `Object` object of `s3` resource

### What I Did

```python
import asyncio
import aioboto3


BUCKET = "test"
PATH = "path.json"
PATH_NEW = "path_{}.json"


async def async_range(count):
    for i in range(count):
        yield(i)


async def main():
    session = aioboto3.session.Session(profile_name="AWSResearch")
    async with session.resource('s3') as resource:
        async for i in async_range(100):
            await resource.Object(BUCKET, PATH_NEW.format(i)).copy_from(CopySource=f"{BUCKET}/{PATH}")

asyncio.run(main())
```

raises an error:

> AttributeError: 'coroutine' object has no attribute 'copy_from'

however the synchronous version of this script works without errors.

**It would be great if you add this method to the library.**

**Comment by terrycain** [comment]
oooh, yeah this most likely needs to be patched in, will have a look into it

**Comment by bubanoid** [comment]
Yeah, you are right. Intermediate variable `res = await resource.Object(BUCKET, PATH_NEW.format(i))` solves the problem.
Thank you!
