### ISSUE TITLE
Crash: ImportError on LinuxAWS docker image with version 9.3.1

### ISSUE THREAD

**Issue by AlexisCra** [terrycain/aioboto3#253]
* Async AWS SDK for Python version:
* Python version: 3.8
* Operating System: Docker image -> public.ecr.aws/lambda/python:3.8

### Description

I'm trying to update a lambda function and required packages versions.

The lambda is crashing at the very beginning when importing aioboto3 (9.3.1) `import aiototo3`

The error is: `ImportError: cannot import name 'is_valid_ipv6_endpoint_url' from 'botocore.endpoint' (/var/runtime/botocore/endpoint.py)`

Everything is working well if I'm using aioboto3<=9.3.0

### What I Did

Build and up the docker image then call the lambda by endpoint.

The stack trace is empty at this point.

Minimal project to reproduce:
![Screenshot 2022-01-24 at 17 22 07](https://user-images.githubusercontent.com/53001247/150822552-ce2bbde3-eab0-4a6d-99b6-cb9b03e896cc.png)

Console output:
![Screenshot 2022-01-24 at 17 23 43](https://user-images.githubusercontent.com/53001247/150822612-ed97cda7-5ff3-4c18-bbfb-4126bac39bd9.png)

Request response data:
![Screenshot 2022-01-24 at 17 26 07](https://user-images.githubusercontent.com/53001247/150823005-3fcccfd0-32dd-4b00-a9cf-18d2aa0fdc44.png)

**Comment by terrycain** [comment]
Im going to guess that the versions of botocore / aiobotocore/ boto3 dont align.

Can you get me the output of pip freeze?
