### ISSUE TITLE
Update aiobotocore version

### ISSUE THREAD

**Issue by chrisBLIT** [terrycain/aioboto3#259]
* Async AWS SDK for Python version: aioboto3 9.3.1

### Description

Issue identified when using the new session.resource, we have some async tests and it seems that we are closing the session twice (we use the mock server shown in examples, plus also the function we are testing with we use the resource.  Seems like because we have 2 of them it tries to clean the session up twice), anyway aiobotocore have released an update to check if the session is None before trying to close it, see below:

https://github.com/aio-libs/aiobotocore/issues/922

is it possible to get a new aioboto3 release which uses the latest version of aiobotocore which has the additional session check.

thanks

**Comment by terrycain** [comment]
v9.4.0 is out, you should be good now

**Comment by dacevedo12** [comment]
there's a new version: aiobotocore 2.2.0

https://github.com/aio-libs/aiobotocore/commit/b7726a4c45b6cdc0a8bf679191ce9c31eb7bd167
