### ISSUE TITLE
CredentialRetrievalError on ECS after a few successful calls

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [terrycain/aioboto3#261]
* Async AWS SDK for Python version: 9.3.1
* Python version: 3.7.11
* Operating System: ECS with Docker Container built on python:3.7-slim-stretch

### Description

Trying to run [aws_collect.py](https://github.com/snowflakedb/SnowAlert/blob/a52b43a7fc2d896f6a93c3f67447d26ef480c440/src/connectors/aws_collect.py) from the SnowAlert project

Everything works fine running on macOS with py3.9 but in ECS with credentials passed as environment variables, out of four times that I tried it in ECS Tasks, 0, 1, 8, and 12 calls are made before a novel exception is raised in [connectors/utils.py:92](https://github.com/snowflakedb/SnowAlert/blob/a52b43a7fc2d896f6a93c3f67447d26ef480c440/src/connectors/utils.py#L92)

~~~
async with aioboto3.Session().client('sts') as sts:
~~~

> botocore.exceptions.CredentialRetrievalError: Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata:

### What I Did

Ran the connector on one of our internal accounts that works fine with 8.3.0 but raises an exception after 12 calls in v9

**Comment by terrycain** [comment]
This would probably be an issue with aiobotocore, as aioboto3 uses its credential handling.

**Comment by sfc-gh-afedorov** [comment]
For posterity, similar newer issue has to do with the metadata API having what appears to be an undocumented rate limit apparent in response header `X-Rate-Limit-Limit: 40.00`. Newer issue showed up as —

> Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve container metadata: Connect timeout on endpoint URL: "http://169.254.170.2/v2/credentials/..."

**Comment by takeda** [comment]
@terricain @sfc-gh-afedorov I just run into this issue. So setting this to higher value can help with this issue?

I read in another place that this can be alleviated by caching and reusing clients, but the aioboto3 pattern which encourages use of `async with` encourages creating clients as needed instead having long running ones.

Is it possible to provide a version to initiate a client without using `__aenter__` and `__aexit__` calls?
