### ISSUE TITLE
Will there be support for SES service? 

### ISSUE THREAD

**Issue by gatewaymanish** [terrycain/aioboto3#268]
* Async AWS SDK for Python version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by terrycain** [comment]
It should support everything boto3 supports
