### ISSUE TITLE
Update aiobotocore version to 2.3.4

### ISSUE THREAD

**Issue by julianogv** [terrycain/aioboto3#269]
Hi there.

I would like to know if it's possible to release a new version using aiobotocore 2.3.4 instead of 2.3.0.

The new aiobotocore 2.3.4 version has a fix (fix connect timeout while getting IAM creds) that is really critical for me (and many others, I believe).

Thanks in advance.

Regards.

**Comment by PhE** [comment]
+1
please relax the dep to something like : `aiobotocore = "^2.3.0"`

**Comment by terrycain** [comment]
This is done, https://pypi.org/project/aioboto3/10.0.0/ is out.
