### ISSUE TITLE
Boto3 .resource are discontinued. What do I do?

### ISSUE THREAD

**Issue by josebsneto** [terrycain/aioboto3#289]
* Async AWS SDK for Python version: latest
* Python version: latest
* Operating System: Linux LTS latest

### Description

I realized that aioboto3 implementations and tests are more .resource than .client. Checking the [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html) lib I saw that the .resource will be discontinued. Is there any strategy to get around this? 

I'm about to use aioboto3 + fastapi async using .client, will I have problems with that? If so, are there any recommendations?

thank you very much

**Comment by terrycain** [comment]
.client works perfectly fine. The main reason it focuses on resources are that they usually required specific patching where as asyncifying the .client methods all happens in aiobotocore. Personally I never use the resource methods either and have no issues using .client

**Comment by josebsneto** [comment]
Does the service .client work fine for Dynamodb? If so, would it be the case to change the readme? https://github.com/terrycain/aioboto3#async-aws-sdk-for-python

**Comment by terrycain** [comment]
Yep as far as im aware all .client's work fine.
