### ISSUE TITLE
Licence makes the library difficult to use

### ISSUE THREAD

**Issue by vlcinsky** [terrycain/aioboto3#29]
While the concept is great, the licence (GPL) is preventing use in many projects.

Please, consider changing the licence to some more commercial friendly one.

**Comment by terrycain** [comment]
https://github.com/terrycain/aioboto3/blob/master/LICENSE

Looks like I didnt update readme

**Comment by terrycain** [comment]
Fixed

**Comment by terrycain** [comment]
Also if you dont mind me asking, what sort of things are you planning to use aioboto3 for? Am pleased its starting to get noticed.

**Comment by vlcinsky** [comment]
@terrycain you made my day. Thanks a lot.

I currently use boto3 (used to use boto(2)) for fetching, transforming and publishing traffic information for few Central European countries. Recently we switched from python 2.7 to python 3.6 including asyncio and there are few areas, which may benefit from this great feature as there are cases, where fetching, processing and publishing has to be synchronized. With asyncio it seems much simpler to do this task very efficiently from coding but also resource point of view.

For this reason I invite your library which gives me a chance to do first testing and see, that it is worth using for future projects.

Thanks for your effort and providing it available under commercial friendly licence.

**Comment by vlcinsky** [comment]
@terrycain Please, update also metadata in setup.py at https://github.com/terrycain/aioboto3/blob/master/setup.py#L46.

This affects the licence reported on pypi.

**Comment by terrycain** [comment]
Good spot. Have updated that, once the builds finish v1.1.1 should appear in pypi eventually.

Nice that sounds like a really interesting project. There are most likely parts of aioboto3 that either are broken or simply not async (as I simply cannot test it all), if you find any please do raise an issue :smile:

**Comment by vlcinsky** [comment]
@terrycain In our case, the most popular AWS technology we use is AWS S3 (I would say 98% of uses). The rest is related to calling Lambda functions.

I guess, asyncio code can improve Lambda functions as it allows using one thread much better for fetching and publishing data while doing some processing. As one pays per runtime, it may improve the efficiency. 

Anyway I wonder, when I will find real case for testing the library. Few weeks ago I was just dreaming of such library at hand and now it appeared under my radar. Next step will come (after I finish other urgent stuff).

**Comment by terrycain** [comment]
The only downside with asyncio in lambdas is that if you up the ram on a lambda, that also ups the cpu and by only running on one core you can potentially use like 20% of the available cpu power available to the lambda

**Comment by vlcinsky** [comment]
@terrycain 
Still one line in `setup.py` to be updated: https://github.com/terrycain/aioboto3/blob/master/setup.py#L40

**Comment by terrycain** [comment]
Ha, i think thats the last one. v1.1.2 is out.

**Comment by vlcinsky** [comment]
It seems fine to me now. Thanks.
