### ISSUE TITLE
Project now requires Python 3.11 

### ISSUE THREAD

**Issue by doneir** [terrycain/aioboto3#295]
As of aioboto3 v11.0.0, aioboto3 will now only work with Python 3.11.

This is due to this commit:

https://github.com/terrycain/aioboto3/commit/d51f669d48507b3feba1597fc18e17ea8e688597

Specifically the line in the pyproject.toml:

https://github.com/terrycain/aioboto3/blob/5c27ba1862edc75387a11a1f0b79b8fac92849e6/pyproject.toml#L27

I assume this is a typo? Hopefully so, as AWS Lambda (as an example) only has official Python images up to Python 3.10

**Comment by terrycain** [comment]
Damn, yeah thats my bad, wasnt thinking, will lower it to 3.9 tonight

**Comment by terrycain** [comment]
v11.0.1 is out now, should fix your issue.
