### ISSUE TITLE
aioboto3 latest version 11.0.1 does not support aiobotocore 2.5.0

### ISSUE THREAD

**Issue by taybur43** [terrycain/aioboto3#297]
Could you please release a version aiboto3 which will support aiobotocore 2.5.0.

**Comment by dacevedo12** [comment]
@terrycain Have you ever considered merging aioboto3 and aiobotocore into an aioboto monorepo?

Not sure how radical of a proposal that is, but just my 2 cents after observing this recurrent issue

Bringing the codebases closer together would likely enable better testing and CI controls to prevent one from falling behind the other. Still, it may also bring some complexity to managing the projects.

Another approach would be to have some automation that automatically submits PRs whenever aiobotocore releases a new version

**Comment by terrycain** [comment]
So I did initially have a bot that would raise PRs when aiobotocore had an update but ultimately I fell unmaintained.

**Comment by taybur43** [comment]
@terrycain Thanks a lot for being too supportive.
