### ISSUE TITLE
Release Needed with upgrade to aiobotocore 2.6.0

### ISSUE THREAD

**Issue by rbrady** [terrycain/aioboto3#311]
* Async AWS SDK for Python version:
* Python version: 3.9.12
* Operating System: OSX

### Description

There was a memory leak issue in boto3 that was fixed as of release 1.27.72.  The current aioboto3 release at pypi (11.2.0) is pinned to aiobotocore 2.5.0 which is pinned to 1.26.76.  In effect, if I want to use aioboto3 in my application, I am forced to use a bad version of boto3.

Please create a new release that is pinned to aiobotocore 2.6.0.

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
Ran poetry add aioboto3

Because no versions of aioboto3 match >11.2.0,<12.0.0
 and aioboto3 (11.2.0) depends on aiobotocore (2.5.0), aioboto3 (>=11.2.0,<12.0.0) requires aiobotocore (2.5.0).
And because aiobotocore (2.5.0) depends on boto3 (>=1.26.76,<1.26.77), aioboto3 (>=11.2.0,<12.0.0) requires boto3 (>=1.26.76,<1.26.77).

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

poetry add aioboto3

**Comment by terrycain** [comment]
v11.3.0 is out supporting aiobotocore 2.6.0
