### ISSUE TITLE
Add basic dynamodb BatchGetItem support

### ISSUE THREAD

**Issue by mpareja** [terrycain/aioboto3#312]
### Description

Dynamo offers a simple API for retrieving a batch of items by ID: [`BatchGetItem`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html). It allows up to 100 items to be retrieved in one round trip. It would be great to have support for this simple operation.

I noticed another issue entitled [BatchGetItem](https://github.com/terrycain/aioboto3/issues/177). This issue conflates a number of concerns, including a background worker for pulling data. I'm _not_ interested in this. Just the ability to make this request-response API call.

**Comment by mpareja** [comment]
I'm going to close this ticket. I realized that `batch_get_item` exists and is part of the top-level client rather than the `Table` I was working with. Sorry for the disruption!

**Comment by LLit888** [comment]
@mpareja I'm running into this same issue, and wanted to learn how I can use BatchGetItem in aioboto3. Could you share how you did it? I would so greatly appreciate it!
