### ISSUE TITLE
aiobotocore dependency is fixed version to patch level - causing dependency resolution issues with otherlibraries that follow patches.

### ISSUE THREAD

**Issue by woodcockr** [terrycain/aioboto3#314]
* Async AWS SDK for Python version: 2.5.4 (desired) 2.5.0 best I can get with aioboto3
* Python version: 3.10
* Operating System: Linux

### Description

The pip dependency resolution is having trouble when installing aioboto3 and s3fs together. s3fs supports aiobotocore 2.5.4 in its most recent version. aioboto3 supports in an earlier version 2.5.0, and in current version 2.6.0 - but nothing in between.

I can see earlier issues (eg. #269) a suggestion to relax this dependency in aioboto3 to be any patch level (2.5.x, 2.6.x). It appeared this was accepted as a suggestion but I note more recent versions appear to have it fully pinned.

Is it possible to relax this patch level fixing?

For the moment I have resolved my particular issue by reverting back to a common earlier version where both use 2.5.0 but it seems, given its patch level, a little peculiar to not pick up on the patches so I thought I would ask.

**Comment by terrycain** [comment]
Sadly relaxing the version isnt really an option, we patch methods of boto3, therefore by pinning a specific version of aiobotocore we get a specific version of boto3.

That being said I can have a look into bodging a 11.1.1 version that would support 2.5.4

**Comment by woodcockr** [comment]
Thanks for the insight. Getting some of these libraries to play nice together can be an interesting exercise. Knowing why is helpful. If you can manage a minor patch that would be helpful.

**Comment by terrycain** [comment]
v11.1.1 should work for you

**Comment by woodcockr** [comment]
Great thanks! pip, aioboto3 (11.1.1) and s3fs (2023.9.2) are all installing nicely together.
