### ISSUE TITLE
Feature Request: New Service support for "bedrock-runtime"

### ISSUE THREAD

**Issue by JackKolb-ElationHealth** [terrycain/aioboto3#317]
* Async AWS SDK for Python version: 11.3
* Python version: 3.10
* Operating System: macOS

### Description

I'm creating a AWS bedrock microservice that uses async boto for nonblocking requests/responses. This microservice is calling AWS bedrock, a relatively new service that provides developer access to LLMs like Claude. 

### What I Did In Boto3

```
bedrock = boto3.client(service_name='bedrock-runtime')
```

### What I Did In AIOBoto3

```
async with self._session.client('bedrock-runtime', config=retry_config, **client_kwargs) as client_instance:
    self._client = client_instance
```
The error :
```
botocore/loaders.py\", line 408, in load_service_model\n raise
 UnknownServiceError(\nbotocore.exceptions.UnknownServiceError: Unknown service: 'bedrock-runtime'.
```

I believe this is due to the current dep version of botocore being a bit older. 

I'm naively suggesting a bump to the version of botocore, but I'm not sure how big of a lift that would be.

Let me know if I can provide any more details, happy to help however.

**Comment by JackKolb-ElationHealth** [comment]
Thinking this through, I think we might need a dep bump in aiobotocore, not botocore. I added a comment to a existing PR to bump the version of botocore within aiobotocore: https://github.com/aio-libs/aiobotocore/issues/1043#issuecomment-1752106511

But I think we may need a version bump here for aiobotocore once it releases.

**Comment by terrycain** [comment]
Yeah once a aiobotocore update is out, i'll update this.

**Comment by YuriyGuts** [comment]
Looks like [aiobotocore 2.7.0 is out](https://github.com/aio-libs/aiobotocore/releases/tag/2.7.0), which pins botocore to  `botocore>=1.31.16,<1.31.65` 🎉

**Comment by dacevedo12** [comment]
Would it be a version bump or does it require wrapping new async codepaths?

I'd assume aiobotocore took care of that but I'm not too familiar with it

**Comment by jakob-keller** [comment]
> Would it be a version bump or does it require wrapping new async codepaths?
> 
> I'd assume aiobotocore took care of that but I'm not too familiar with it

There were no new async codepaths, merely a version bump. That should all be taken care of in `aiobotocore==2.7.0`.

**Comment by terrycain** [comment]
Sorry about the delay, v12.0.0 is out.
