### ISSUE TITLE
Is is possible to have callbacks when uploading objects?

### ISSUE THREAD

**Issue by treuille** [terrycain/aioboto3#60]
Might it be possible to get progress callbacks for `upload_file` and `upload_fileobj` as in `boto3`?

(This issue was created at the recommendation of @terrycain in aio-libs/aiobotocore#584.)

Thank you!

**Comment by terrycain** [comment]
Yeah, the solution would be for me to change the current upload_fileobj to do a multipart upload instead of a put_object.

**Comment by terrycain** [comment]
Can you try the `multipart_upload_60` branch. It "should" have the required fixes... also it knows none of the error conditions when doing multipart uploads as I don't know what they would be so have just left in a default "404" type error for now.

**Comment by treuille** [comment]
@terrycain : Thank you so much for getting back so quickly. My team is on a tight deadline to deliver a feature and so I won't have time to play with this until next week. (We're just going to settle for no progress :/ for now.)

However, I will definitely check this out when we have a breather -- probably next week. 

Thank you again for the rapid response. 💯

**Comment by terrycain** [comment]
No problem, it technically works as I had some tests run on it but it'll sit in that branch until you can test it as I'd rather have someone who has real-life uses for it play around with it :smile:

**Comment by treuille** [comment]
Hey Terry:

Unfortunately, I won't be able to test this feature :/ as we're backporting
our code base to 2.7 and are disassbling the infrastructure that would even
have allowed us to test it. I know... I know!! ;-)

Thank you again for the rapid turnaround. We were very impressed how
responsively your project fulfils feature requests! :-)

Adrien

**Comment by terrycain** [comment]
Is fixed in v5.0.0
